version: '2'
services:
    web:
        image: alexellis2/nginx-arm
        ports:
            - "8000:80"
        restart: always
        container_name: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./git/hello:/git/hello"
    php:
        image: shaula/rpi-php7-fpm
        restart: always
        container_name: php
        volumes:
            - "./git/hello:/git/hello"
